### PR TITLE
Fix #230: Update tor test-plan to check for notarization and static binary

### LINKED ISSUE #230: Update tor test-plan to check for notarization and static binary
#### Summary:

Currently we only check if the tor client binary passed the codesign check. Binaries also need to be notarized on Catalina and Big Sur to avoid any prompts.

On Linux, we create a static binary. Testing if the binary is static validates that the binary will work without installing any additional libraries.

### PR DESCRIPTION
**Pull request by jumde**
Fix #230

### CODE REVIEW

**Comment by stephendonner** [comment]
LGTM, but just in case there's something I'm missing, I'll defer to the rest of the team for the _official) r+ (thanks and sorry!)

**Review by srirambv — APPROVED** [review]
++

**Review by kjozwiak — APPROVED** [review]
LGTM++

**Comment by kjozwiak** [comment]
Thanks for the reviews @stephendonner & @srirambv 👍 Merging. Thanks for getting this added @jumde.

**Pull request merged**
