### PR TITLE
Swap 1Password in for LastPass

### PR DESCRIPTION
**Pull request by stephendonner**
Fixes https://github.com/brave/qa-resources/issues/537

### CODE REVIEW

**Comment by stephendonner** [comment]
Note: both `1Password` and `LastPass` have the `Brave has not reviewed this extension...` in their install-prompt warning text (and our tests are meant to differentiate), but I'll fix that in a separate issue (please?)

😁

**Comment by kjozwiak** [comment]
> Note: both `1Password` and `LastPass` have the `Brave has not reviewed this extension...` in their install-prompt warning text (and our tests are meant to differentiate), but I'll fix that in a separate issue (please?)
> 
> 😁

Believe there's discussions of just removing the warning/editing it via https://bravesoftware.slack.com/archives/C2J3NA3L7/p1679586946528949. But not 100% sure when/if those changes will actually happen.

**Review by kjozwiak — APPROVED** [review]
Change LGTM 👍

**Comment by stephendonner** [comment]
Thx as always @kjozwiak and @srirambv ❤️

**Pull request merged**
