### PR TITLE
Add checks for adblock lists and filters

### LINKED ISSUE #503: add brave://adblock tests to manual passes
We should add some tests for brave://adblock (brave://settings/shields/filters) to our manual passes to ensure this page works as expected with major Chromium bumps.

### PR DESCRIPTION
**Pull request by LaurenWags**
Fix #503

Added tests as suggested in https://github.com/brave/qa-resources/issues/503#issuecomment-1420031840.

### CODE REVIEW

**Review by antonok-edm — APPROVED** [review]
:smiley:

**Review by kjozwiak — APPROVED** [review]
LGTM 👍 However, we need to add a few cases to handle upgrades. For example:

* ensure that `Custom Filters` are retained when upgrading
* ensure that `Custom Lists` are retained when upgrading

@LaurenWags do you prefer doing the above in a new issue or we can just edit this PR. Either way works.

**Review by stephendonner — APPROVED** [review]
Looks great to me also, thanks for adding these!  👍 

Land now w/followup later, or incorporate, as you see fit!  Either way, r+

**Review by stephendonner — APPROVED** [review]
Looks great to me!  Only nit is the upper-casing of `Filters` and `Lists`.

i.e.

* s/Custom Filters/Custom filters
* s/Custom Lists/Custom lists

Screen Shot 2023-02-10 at 11 08 43 AM

**Pull request merged**
