### PR TITLE
Fix iOS template and test run

### LINKED ISSUE #105: Update iOS tests for new version

### PR DESCRIPTION
**Pull request by srirambv**
Fixes #105

### CODE REVIEW

**Comment by kjozwiak** [comment]
@srirambv is this working for you? I pull this branch but I keep getting the followng

```
Create test runs for:

1. Laptop Release
2. Laptop Per-release Checklist
3. iOS
4. Android

Choose the platform for which you want to generate the test run: 3
Generating test runs for iOS  1.7.2
Release Note:

Release Checklist:
 - [ ] Tabs bar shown when a favourite is loaded after deleting browser data. ([#591](https://github.com/brave/brave-ios/issues/591))
https://github.com/brave/brave-ios/issues/591
 - [ ] Re-enable HTTPSE UI. ([#653](https://github.com/brave/brave-ios/issues/653))
https://github.com/brave/brave-ios/issues/653
 - [ ] Saving a GIF doesn't work (Saves as still image). ([#659](https://github.com/brave/brave-ios/issues/659))
https://github.com/brave/brave-ios/issues/659
 - [ ] Can't move bookmarks inside of a folder. ([#687](https://github.com/brave/brave-ios/issues/687))
https://github.com/brave/brave-ios/issues/687
Traceback (most recent call last):
  File "brave_testrun_generator.py", line 472, in <module>
    ios_testruns()
  File "brave_testrun_generator.py", line 269, in ios_testruns
    print(line)
  File "C:\Users\kjozwiak\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 29: character maps to <undefined>
```

Using the following commit:

```
kjozwiak@DESKTOP-D7HAE1M MINGW64 /c/brave/qa-resources (iOS)
$ git log -1
commit 398a40d47ce4cd848eea14b57e1bf89f18619dc1 (HEAD -> iOS)
Author: srirambv <sriram@brave.com>
Date:   Wed Jan 16 07:43:04 2019 +0530

    Fix iOS template and test run
```

**Comment by kjozwiak** [comment]
Hmm I think it's failing due to https://github.com/brave/brave-ios/issues/688. I don't think the script can recognize the `→` character. Hence, receiving the following error:

```UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 29: character maps to <undefined>```

**Comment by srirambv** [comment]
Works fine for me on Linux. Could be Windows specific issue with Python unable to parse it. Excluding the issue title I think it works just fine

**Comment by srirambv** [comment]
@kjozwiak do you still see the same issue on Windows?

**Comment by srirambv** [comment]
Fixed issue with wrong variable and title. This should be good to merge now. Tested it and generated test runs as well for 1.8 release on iOS.

**Comment by srirambv** [comment]
Merging it. I'll create a new pr with fix if it still fails on Windows.

**Pull request merged**
