### PR TITLE
Adds startup checks for Brave endpoints

### LINKED ISSUE #239: adding checks to make sure Brave only contacts known endpoints at startup
Adding checks to ensure that Brave only contacts `*.brave.com` endpoints at launch. We've seen Chromium add new calls before with major CR bumps so we need to catch these early and either remove or route through a `*.brave.com` proxy.

### PR DESCRIPTION
**Pull request by kjozwiak**
Fix #239

### CODE REVIEW

**Review by LaurenWags — APPROVED** [review]
++

**Review by stephendonner — APPROVED** [review]
r+; LGTM too!

**Comment by kjozwiak** [comment]
Thanks @StephenBass & @LaurenWags 👍 I'll wait for @srirambv re: mobile and merge if all good.

**Review by srirambv — APPROVED** [review]
++

**Pull request merged**
