### PR TITLE
Add IPFS WikiTemplate & update testscript

### LINKED ISSUE #322: Add IPFS test sheet
Use https://github.com/brave/brave-browser/issues/16669 as a reference for adding a wiki template file

### LINKED ISSUE #323: Add IPFS tests to test generator script
Add IPFS tests to test generator script to avoid manual work

### PR DESCRIPTION
**Pull request by srirambv**
Closes #322 
Closes #323 

PR contains:
* New wiki template file for IPFS based on https://github.com/brave/brave-browser/issues/16669
* Update Test script to generate test runs for IPFS releases
* Some minor tweaks to make the console output look nice

### CODE REVIEW

**Review by stephendonner — APPROVED** [review]
Thanks for doing this, @srirambv - it looks (great) to me (I haven't run it, yet).  Conditional r+, assuming someone runs it or I get a chance to run it.

I was hoping to get further tweaks into https://github.com/brave/brave-browser/wiki/IPFS-Features before we incorporated it into a test script like this, but I won't rathole that here, and will submit follow-up PRs when I have a little more breathing room.

@kjozwiak mind running through this one, as you're more familiar with the setup and how it's supposed to work?  It's clear I need to eke out some time to try this out.

**Comment by srirambv** [comment]
@stephendonner we can always do a follow up PR for the wiki template update. Once @kjozwiak  runs through it I'll get this merged. You can add a follow up PR for the template file whenever you have time.

**Review by kjozwiak — CHANGES_REQUESTED** [review]
Looks like there's an issue when attempting to create the Windows template as per:

```
Traceback (most recent call last):
  File "brave_testrun_generator.py", line 917, in <module>
    ipfs_testruns(ipfskey)
  File "brave_testrun_generator.py", line 811, in ipfs_testruns
    body=windows_template,
NameError: name 'windows_template' is not defined
```

Looks like `windows_template` isn't defined.

**Review by kjozwiak — APPROVED** [review]
LGTM 👍 Nice work!

**Pull request merged**
